DEV-002 run commands npx create-react-app .  and npm install
ettienekorayyi/poc-code-sydney pull request #2
Opened 2020-04-13 12:04 UTC by juliaCold

## Rationale

Run commands:
- npx create-react-app .
- npm install axios
- npm install react-icons
- npm install react-router-dom

## Advice for Reviewers & Testing Notes

- npm start 

- Also, the original README.md was removed because there was a conflict when running npx create-react-app .

## Screenshots:

![Screenshot 2020-04-13 at 21 51 08](https://user-images.githubusercontent.com/39728371/79118766-178de200-7dd2-11ea-917f-05d7978555f7.png)

## Task Name

- DEV-002 Project Scaffold

## Linting Checklist

- [x] No commented code
- [x] Code Formatted nicely (Prettier)
- [x] PR your own code before you assign reviewers

2020-04-13 12:16 UTC, ghost requested changes

2020-04-13 12:16 UTC, promie commented on package.json
> +    "react-scripts": "3.4.1"
Where are the packages that you've installed for axios, react-router-dom and react-icons?

2020-04-14 10:10 UTC, juliaCold commented on package.json
> +    "react-scripts": "3.4.1"
Reinstall:
![Screenshot 2020-04-14 at 20 06 39](https://user-images.githubusercontent.com/39728371/79213155-04d7e380-7e8c-11ea-9a47-c826034d6cd7.png)

2020-04-14 11:48 UTC, ghost approved these changes

2020-04-14 12:44 UTC, merged